name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [v2]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: "pnpm"

      - name: Enable corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm -s tsc --noEmit

      - name: Test
        run: pnpm -s test
